server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**



#http://localhost:8888 - conf
#http://localhost:8761 - disc
#http://localhost:8222 - gateway
#http://localhost:8111 - user
#http://localhost:8000 - auth